version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./dev_mybiotracker.db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=true
    volumes:
      - ./backend:/app
      - dev_data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  dev_data:
  redis_dev_data: